name: Java CI with Maven

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses: actions/upload-artifact@v3
      with:
       name: buildArtifact
       path: target/*.war
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        context: .
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/springboot:latest 

  deploy: 
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy Application using SSH
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      env:
       WELCOME: "ssh scp ssh pipelines"
       LASTSSH: "Doing something after copying"
      with:
       host: '52.90.163.121'
       user: 'joergjehringvod'
       pass: 'ingvod0A@2uqz2'
       port: 42006  
       connect_timeout: 10s
       first_ssh: |
        rm -rf /tmp/Docker
        mkdir -p /tmp/Docker
       scp: |
        'Dockerfile' => /tmp/Docker
       last_ssh: |
        docker run -d ${{ secrets.DOCKERHUB_USERNAME }}/springboot:latest 
